linters-settings:
  gofumpt:
    simplify: true

  misspell:
    locale: US

  staticcheck:
    checks: ['all', '-ST1005', '-ST1000', '-SA4000', '-SA9004', '-SA1019', '-SA1008', '-U1000', '-ST1016']

linters:
  disable-all: true
  enable:
    - durationcheck
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - prealloc

issues:
  exclude-use-default: false
  exclude:
    - should have comment or be unexported
    - should have a package comment
    - error strings should not be capitalized or end with punctuation or a newline
