version: "2"
linters:
  default: none
  enable:
    - durationcheck
    - gocritic
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -SA1008
        - -SA1019
        - -SA4000
        - -SA9004
        - -ST1000
        - -ST1005
        - -ST1016
        - -U1000
        - -ST1005
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: should have comment or be unexported
      - path: (.+)\.go$
        text: should have a package comment
      - path: (.+)\.go$
        text: error strings should not be capitalized or end with punctuation or a newline
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
