# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: warp

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy -compat=1.21
builds:
  -
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - --tags=kqueue
    ldflags:
      - -s -w -X github.com/minio/warp/pkg.ReleaseTag={{.Tag}} -X github.com/minio/warp/pkg.CommitID={{.FullCommit}} -X github.com/minio/warp/pkg.Version={{.Version}} -X github.com/minio/warp/pkg.ShortCommitID={{.ShortCommit}} -X github.com/minio/warp/pkg.ReleaseTime={{.Date}}
archives:
  -
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - warp_logo.png
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: 'snapshot-{{ time "2006-01-02" }}'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    vendor: MinIO Inc.
    homepage: https://github.com/minio/warp
    maintainer: MinIO <minio@minio.io>
    description: S3 API Benchmark Tool
    license: GNU Affero General Public License v3.0
    formats:
      - deb
      - rpm
    contents:
      # Basic file that applies to all packagers
      - src: systemd/warp.service
        dst: /etc/systemd/system/warp.service
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
dockers:
  -
    # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    dockerfile: Dockerfile.release
    image_templates:
      - "minio/warp:{{ .Tag }}"
      - "minio/warp:latest"
