---
apiVersion: v1
kind: Service
metadata:
  name: warp
  labels:
    app: warp
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 7761
      name: warp
  selector:
    app: warp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: warp
  labels:
    app: warp
spec:
  serviceName: warp
  podManagementPolicy: Parallel
  replicas: 4
  selector:
    matchLabels:
      app: warp
  template:
    metadata:
      name: warp
      labels:
        app: warp
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - warp
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: warp
          image: "minio/warp:latest"
          imagePullPolicy: Always
          args:
            - client
          ports:
            - name: http
              containerPort: 7761
