apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "warp.fullname" . }}
  labels:
    {{- include "warp.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: {{ include "warp.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ include "warp.imageVersion" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "{{ .Values.warpConfiguration.operationToBenchmark }}"
          - "--warp-client=warp-{0...{{ sub .Values.replicaCount 1 }}}.warp.{{ .Release.Namespace }}"
        {{- range $k, $v := .Values.warpJobArgs }}
          - --{{ $k }}={{ $v }}
        {{- end }}
        env:
          - name: WARP_HOST
            value: {{ .Values.warpConfiguration.s3ServerURL | quote }}
        {{- if .Values.warpConfiguration.s3ServerTLSEnabled }}
          - name: WARP_TLS
            value: "true"
        {{- end }}
          - name: WARP_REGION
            value: {{ .Values.warpConfiguration.s3ServerRegion | quote }}
          - name: WARP_ACCESS_KEY
            value: {{ .Values.warpConfiguration.s3AccessKey | quote }}
          - name: WARP_SECRET_KEY
            value: {{ .Values.warpConfiguration.s3SecretKey | quote }}
      {{- if .Values.serverResources }}
        resources: {{- toYaml .Values.serverResources | nindent 12 }}
      {{- end }}
      {{- if .Values.securityContext }}
        securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
      {{- end }}
    {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "warp.serviceAccountName" . }}
    {{- end }}
    {{- if .Values.podSecurityContext }}
      securityContext: {{- .Values.podSecurityContext | toYaml | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity: {{- .Values.affinity | toYaml | nindent 8 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations: {{- .Values.tolerations | toYaml | nindent 8 }}
    {{- end }}
  backoffLimit: 4
