apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warp.fullname" . }}-credentials
  labels:
    {{- include "warp.labels" . | nindent 4 }}
data:
  access_key: {{ .Values.warpConfiguration.s3AccessKey | b64enc }}
  secret_key: {{ .Values.warpConfiguration.s3SecretKey | b64enc }}
